local Plug = vim.fn['plug#']

vim.fn['plug#begin']('~/.vim/plugged')

Plug('morhetz/gruvbox')
Plug('nvim-treesitter/nvim-treesitter', {['do'] = ':TSUpdate'})
Plug('nvim-lualine/lualine.nvim')
Plug('sheerun/vimrc')
Plug('sheerun/vim-polyglot')
Plug('preservim/nerdcommenter')
Plug('preservim/nerdtree')
Plug('Xuyuanp/nerdtree-git-plugin')
Plug('PhilRunninger/nerdtree-visual-selection')
Plug('ryanoasis/vim-devicons')
Plug('glepnir/dashboard-nvim')
Plug('junegunn/fzf', {['do'] = function() vim.fn['fzf#install']() end})
Plug('junegunn/fzf.vim')
Plug('voldikss/vim-floaterm')
Plug('iamcco/markdown-preview.nvim', {['do'] = 'cd app && yarn install'})
Plug('tpope/vim-fugitive')
Plug('neovim/nvim-lspconfig')
Plug('prettier/vim-prettier', {['do'] = 'yarn install --frozen-lockfile --production' })
Plug('nvim-lua/plenary.nvim')
Plug('lewis6991/gitsigns.nvim')
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('saadparwaiz1/cmp_luasnip')
Plug('L3MON4D3/LuaSnip')
Plug('rmagatti/goto-preview')

vim.fn['plug#end']()
